### ISSUE TITLE
flow-language-server on init

### ISSUE THREAD

**Issue by ykagan** [flowtype/ide-flowtype#17]
Getting the following error when trying initialize the flow server with debug logging turned on:

`[ERROR] flow-language-server - unhandledRejection { Error: Unhandled method window/showMessageRequest
    at new ResponseError (C:\Users\ykagan\.atom\packages\ide-flowtype\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
    at handleResponse (C:\Users\ykagan\.atom\packages\ide-flowtype\node_modules\vscode-jsonrpc\lib\main.js:421:48)
    at processMessageQueue (C:\Users\ykagan\.atom\packages\ide-flowtype\node_modules\vscode-jsonrpc\lib\main.js:249:17)
    at Immediate.<anonymous> (C:\Users\ykagan\.atom\packages\ide-flowtype\node_modules\vscode-jsonrpc\lib\main.js:233:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) code: -32601 }`

Flow version: 0.53.1
Atom: 1.21.0-beta0 x64
OS: Windows 10

**Comment by wbinnssmith** [comment]
hi @ykagan! We're still ironing out a few last issues with Windows so hang tight. I appreciate the stack trace!

I'll report back here when things are good to go. Thanks for your patience :)

**Comment by mikecousins** [comment]
Any progress on this one? 1.21 stable came out today but it's still not working for me on Windows.

**Comment by leocavalcante** [comment]
At `C:\Users\<Your User>\.atom\packages\ide-flowtype\lib\main.js`
Add a:
```js
connection.onShowMessageRequest(() => console.log(arguments))
```
Right after (inside):
```js
preInitialization(connection)
```
Then it will log more info.

Here the problem was:
`Supplied path to flow was not absolute. Specify a complete path to the flow binary or leave the option empty for Flow to be managed for you.`

Because I tried:
`path to flow $PROJECT_ROOT\node_modules\.bin\flow.cmd`
It can't handle `$PROJECT_ROOT`
<hr>
The problem is that, even fixing it to a absolute path, I'm getting:

```
flow is running on a different directory.
server_root: C:\Users\Leo\Desktop\test-atom
client_root: c:\Users\Leo\Desktop\test-atom
```

Probably because of the capital C 😅
