### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by samora** [flowtype/ide-flowtype#35]
[Enter steps to reproduce:]

1. ... Open an Ember project
2. ... Error appears after a while

**Atom**: 1.21.0-beta2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-flowtype](https://github.com/flowtype/ide-flowtype) package 0.17.4

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/samoradake/.atom/packages/ide-flowtype/node_modules/vscode-jsonrpc/lib/main.js:604

Error: Connection is closed.
    at /packages/ide-flowtype/node_modules/vscode-jsonrpc/lib/main.js:129:28)
    at throwIfClosedOrDisposed (/packages/ide-flowtype/node_modules/vscode-jsonrpc/lib/main.js:604:19)
    at Object.sendNotification (/packages/ide-flowtype/node_modules/vscode-jsonrpc/lib/main.js:658:13)
    at LanguageClientConnection._sendNotification (/packages/ide-flowtype/node_modules/atom-languageclient/build/lib/languageclient.js:231:15)
    at LanguageClientConnection.didChangeWatchedFiles (/packages/ide-flowtype/node_modules/atom-languageclient/build/lib/languageclient.js:136:10)
    at ServerManager.projectFilesChanged (/packages/ide-flowtype/node_modules/atom-languageclient/build/lib/server-manager.js:257:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/project.js:297:40
    at PathWatcher.onNativeEvents (/Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:671:15)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:448:26)
    at handler (/Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:177:15)
```

### Commands

```
     -1:31 core:copy (input.hidden-input)
     -1:30.5.0 core:paste (input.hidden-input)
     -0:57 editor:delete-line (input.hidden-input)
  2x -0:52.6.0 core:backspace (input.hidden-input)
  2x -0:48.6.0 core:move-down (input.hidden-input)
  2x -0:48.1.0 autocomplete-plus:confirm (input.hidden-input)
  3x -0:40.2.0 core:move-right (input.hidden-input)
     -0:35.5.0 core:backspace (input.hidden-input)
     -0:35.1.0 editor:newline (input.hidden-input)
     -0:30.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.4.0 
busy-signal 1.4.3 
go-debug 1.5.2 
go-plus 5.5.5 
go-signature-statusbar 1.2.3 
ide-csharp 0.6.0 
ide-ember 0.4.2 
ide-flowtype 0.17.4 
ide-go 0.4.0 
ide-java 0.6.5 
ide-json 0.1.0 
ide-typescript 0.6.1 
ide-vue 0.1.7 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
```

**Comment by carstn** [comment]
For reference, the same issue (ConnectionError from the `vscode-jsonrpc` package) is affecting [ide-typescript (#17)](https://github.com/atom/ide-typescript/issues/17), [ide-java (#29)](https://github.com/atom/ide-java/issues/29), [ide-html (#9)](https://github.com/liuderchi/ide-html/issues/9), and others.
